services:
  - type: web
    name: omnispect-x-api
    runtime: docker
    repo: https://github.com/dmustapha/omnispect-x
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: OKX_BASE_URL
        value: https://okx-proxy.gnk942nvbx.workers.dev
      - key: OKX_API_KEY
        sync: false
      - key: OKX_SECRET_KEY
        sync: false
      - key: OKX_PASSPHRASE
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: PINATA_JWT
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: UNISWAP_API_KEY
        sync: false
      - key: X_LAYER_RPC
        value: https://rpc.xlayer.tech
      - key: LINEAGE_CONTRACT
        sync: false
      - key: CORS_ORIGIN
        value: https://omnispect-x.vercel.app
